organization:
  country: 'US'
  city: 'Los Angeles'
  state: 'California'
  ou: 'Kubernetes The Hard Way - AWS'
  o: 'Kubernetes'

remote_user: 'ubuntu'

kube_apiserver_port: 6443

aws:
  region: 'us-west-1'

network:
  cidr_block:                   '10.240.0.0/24'
  pod_cidr_block:               '10.200.0.0/16'
  service_cluster_ip_range:     '10.32.0.0/24'
  internal_cluster_services_ip: '10.32.0.1'

controllers:
  - hostname: 'controller-0'
    internal_ip: '10.240.0.10'
    aws_hostname: 'ip-10-240-0-10'
    instance_type: 't2.micro'

  # - hostname: 'controller-1'
  #   internal_ip: '10.240.0.11'
  #   aws_hostname: 'ip-10-240-0-11'
  #   instance_type: 't2.micro'

  # - hostname: 'controller-2'
  #   internal_ip: '10.240.0.12'
  #   aws_hostname: 'ip-10-240-0-12'
  #   instance_type: 't2.micro'

workers:
  - hostname: 'worker-0'
    internal_ip: '10.240.0.20'
    aws_hostname: 'ip-10-240-0-20'
    instance_type: 't2.micro'
    pod_cidr: '10.200.0.0/24'

  # - hostname: 'worker-1'
  #   internal_ip: '10.240.0.21'
  #   aws_hostname: 'ip-10-240-0-21'
  #   instance_type: 't2.micro'
  #   pod_cidr: '10.200.1.0/24'

  # - hostname: 'worker-2'
  #   internal_ip: '10.240.0.22'
  #   aws_hostname: 'ip-10-240-0-22'
  #   instance_type: 't2.micro'
  #   pod_cidr: '10.200.2.0/24'
