organization:
  country: 'US'
  city: 'Los Angeles'
  state: 'California'
  ou: 'Kubernetes The Hard Way - AWS'
  o: 'Kubernetes'

internal_cluster_services_ip: '10.32.0.1'

controllers:
  - { hostname: 'controller-0', internal_ip: '10.240.0.10', aws_hostname: 'ip-10-240-0-10' }
  # - { hostname: 'controller-1', internal_ip: '10.240.0.11', aws_hostname: 'ip-10-240-0-11' }
  # - { hostname: 'controller-2', internal_ip: '10.240.0.12', aws_hostname: 'ip-10-240-0-12' }

workers:
  - { hostname: 'worker-0', internal_ip: '10.240.0.20', aws_hostname: 'ip-10-240-0-20' }
  # - { hostname: 'worker-1', internal_ip: '10.240.0.21', aws_hostname: 'ip-10-240-0-21' }
  # - { hostname: 'worker-2', internal_ip: '10.240.0.22', aws_hostname: 'ip-10-240-0-22' }
